// flow-typed signature: d084640667e4c760183fba83e33b43ed
// flow-typed version: <<STUB>>/lodash.isplainobject_v^4.0.6/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.isplainobject'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.isplainobject' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'lodash.isplainobject/index' {
  declare module.exports: $Exports<'lodash.isplainobject'>
}
declare module 'lodash.isplainobject/index.js' {
  declare module.exports: $Exports<'lodash.isplainobject'>
}
